
     [build]
       command = "npm install"
       functions = "functions"
       publish = "public"

     [[redirects]]
       from = "/chat"
       to = "/.netlify/functions/chat"
       status = 200
       force = true
